"""Change product variation and package structure

Revision ID: d87ff2b2c19e
Revises: 2def68e4fd05
Create Date: 2025-09-22 15:59:51.960980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87ff2b2c19e'
down_revision = '2def68e4fd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('package_quantity', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product_packages', ['package_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('product_packages')
    # ### end Alembic commands ###
