"""Initial migration

Revision ID: initial
Revises:
Create Date: 2025-09-20 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ozon_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_name', sa.String(length=255), nullable=False),
    sa.Column('cluster_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ozon_warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=255), nullable=False),
    sa.Column('warehouse_type', sa.String(length=50), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['ozon_clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('package_quantity', sa.Integer(), nullable=True),
    sa.Column('variation_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('destination_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('shipment_date', sa.DateTime(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['ozon_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_number')
    )
    op.create_table('our_warehouse_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('unpacked_quantity', sa.Integer(), nullable=True),
    sa.Column('packed_quantity', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variation_id')
    )
    op.create_table('ozon_fbo_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('available_stock_count', sa.Integer(), nullable=True),
    sa.Column('valid_stock_count', sa.Integer(), nullable=True),
    sa.Column('transit_stock_count', sa.Integer(), nullable=True),
    sa.Column('reserved_amount', sa.Integer(), nullable=True),
    sa.Column('turnover_grade', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['ozon_clusters.id'], ),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['ozon_warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variation_id', 'cluster_id', 'warehouse_id', name='_variation_cluster_warehouse_uc')
    )
    op.create_table('shipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'variation_id', name='_shipment_variation_uc')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_movements')
    op.drop_table('shipment_items')
    op.drop_table('ozon_fbo_stocks')
    op.drop_table('our_warehouse_stocks')
    op.drop_table('shipments')
    op.drop_table('product_variations')
    op.drop_table('products')
    op.drop_table('ozon_warehouses')
    op.drop_table('product_categories')
    op.drop_table('ozon_clusters')
    # ### end Alembic commands ###